(function(){
const q=id=>document.getElementById(id);
let toastTimer=null;
function toast(message,isError=false){const el=q('toast');if(!el)return;el.textContent=message;el.classList.toggle('error',isError);el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function setAssetStatus(kind,message,status='ok'){const el=q(kind==='bg'?'bgStatus':'mediaStatus');if(!el)return;el.className='asset-status '+(status==='idle'?'idle':status==='error'?'error':'');el.textContent=message}
function setProjectStatus(message){const el=q('projectStatus');if(el)el.textContent=message}
function fmtBytes(n){if(!Number.isFinite(n))return'';const u=['B','KB','MB','GB'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`}
function validateFile(file,kind){if(!file)return'No file selected.';if(kind==='bg'&&!file.type.startsWith('image/'))return'Background must be an image.';if(kind==='media'&&!(file.type.startsWith('video/')||file.type.startsWith('image/')))return'Choose an image or video file.';return''}
function loadAsset(file,kind){const error=validateFile(file,kind);if(error){setAssetStatus(kind,error,'error');toast(error,true);return}setAssetStatus(kind,`Loading ${file.name}…`,'idle');setProjectStatus('Loading asset…');const reader=new FileReader();reader.onerror=()=>{setAssetStatus(kind,'File could not be read.','error');setProjectStatus('Ready · load failed');toast('File could not be read.',true)};reader.onload=()=>{const data=reader.result;if(kind==='bg'){state.bgData=data;state.bgSrc=data;els.sceneBg.src=data;state.scene='custom';q('scenePreset').value='custom';els.guide.style.display='block';setAssetStatus('bg',`✓ Background loaded · ${file.name} · ${fmtBytes(file.size)}`);setProjectStatus('Background loaded');toast('✓ BACKGROUND LOADED');}else{if(currentObjectUrl)URL.revokeObjectURL(currentObjectUrl);currentObjectUrl=URL.createObjectURL(file);const type=file.type.startsWith('video/')?'video':'image';state.mediaData=data;q('mediaMode').value=type==='video'?'localVideo':'localImage';setMedia(type,currentObjectUrl,data);setAssetStatus('media',`✓ ${type==='video'?'Video':'Image'} loaded · ${file.name} · ${fmtBytes(file.size)}`);setProjectStatus(`${type==='video'?'Video':'Image'} loaded`);toast(`✓ ${type==='video'?'VIDEO':'IMAGE'} LOADED`);} };reader.readAsDataURL(file)}
function saveSettings(){try{const keys=['scene','opacity','brightness','contrast','blend','spill','reflection','bgBrightness','scale','x','y','rot','beam','beamIntensity','beamWidth','beamSoftness','particles','particleAmount','particleSpeed','particleSize','particleOpacity','loop','muted'];const saved={};keys.forEach(k=>saved[k]=state[k]);localStorage.setItem('projection-v1-1-settings',JSON.stringify(saved));setProjectStatus('Project settings saved');toast('✓ PROJECT SETTINGS SAVED')}catch(e){toast('Could not save settings.',true)}}
function restoreSettings(){try{const raw=localStorage.getItem('projection-v1-1-settings');if(!raw){toast('No saved settings yet.',true);return}Object.assign(state,JSON.parse(raw));syncControls();applyLook();q('scenePreset').value=state.scene==='custom'?'custom':'rubik';els.guide.style.display=state.scene==='custom'?'block':'none';setProjectStatus('Saved settings restored');toast('✓ SETTINGS RESTORED')}catch(e){toast('Saved settings could not be restored.',true)}}
function install(){const bg=q('uploadBg'),media=q('uploadMedia');if(bg){bg.classList.add('file-input');bg.onclick=()=>{bg.value=''};bg.onchange=e=>{const f=e.target.files&&e.target.files[0];loadAsset(f,'bg')}}if(media){media.classList.add('file-input');media.onclick=()=>{media.value=''};media.onchange=e=>{const f=e.target.files&&e.target.files[0];loadAsset(f,'media')}}
const mediaMode=q('mediaMode');if(mediaMode){mediaMode.onchange=e=>{const v=e.target.value;q('remoteGroup').classList.toggle('hidden',!v.startsWith('remote'));q('localUploadGroup').classList.remove('hidden');if(v==='youtube'){setMedia('youtube','https://www.youtube.com/embed/hXD8itTKdY0?autoplay=1&mute=1&loop=1&controls=0&playlist=hXD8itTKdY0');setAssetStatus('media','Original Rubik Sota media active.','idle');toast('Original media restored')}}}
q('playBtn').onclick=()=>{if(state.mediaType==='video'){els.video.play().then(()=>{setProjectStatus('Video playing');toast('▶ VIDEO PLAYING')}).catch(()=>toast('Video playback was blocked.',true))}else toast('Play controls apply to local/direct video.')} ;q('pauseBtn').onclick=()=>{if(state.mediaType==='video'){els.video.pause();setProjectStatus('Video paused');toast('Ⅱ VIDEO PAUSED')}else toast('Pause controls apply to video.')} ;q('restartBtn').onclick=()=>{if(state.mediaType==='video'){els.video.currentTime=0;els.video.play().catch(()=>{});setProjectStatus('Video restarted');toast('↻ VIDEO RESTARTED')}else toast('Restart controls apply to video.')};
q('saveProjectBtn').onclick=saveSettings;q('restoreProjectBtn').onclick=restoreSettings;
const oldExport=exportHTML;q('exportHtmlBtn').onclick=()=>{oldExport();setProjectStatus('Standalone HTML exported');toast('✓ HTML EXPORTED')};const oldShot=screenshot;q('screenshotBtn').onclick=()=>{oldShot();setProjectStatus('Preparing PNG…');toast('Preparing screenshot…')};const oldCopy=copyEmbed;q('copyEmbedBtn').onclick=()=>{oldCopy();setProjectStatus('Embed prepared')};const oldRecord=recordScreen;q('recordBtn').onclick=()=>{oldRecord();setProjectStatus('Recording requested')};const oldStop=stopRecording;q('stopRecordBtn').onclick=()=>{oldStop();setProjectStatus('Recording stopping…')};
setAssetStatus('bg','No custom background loaded.','idle');setAssetStatus('media','Original Rubik Sota media active.','idle');setProjectStatus('Ready · V1.1 upload fix active');}
document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));
})();